[package]
name = "aoc-2019-07"
version = "0.1.0"
authors = ["Josh W Lewis <josh.w.lewis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
